name: prep-tracker-prod

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    image: prep-tracker-web-prod
    restart: unless-stopped
    networks:
      - prep-tracker-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: prep-tracker-api-prod
    restart: unless-stopped
    environment:
      PORT: ${API_PORT}
      CLIENT_ORIGIN: http://localhost:${NGINX_PORT}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
    depends_on:
      - postgres
    networks:
      - prep-tracker-network

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/docker/prod/postgres:/var/lib/postgresql/data
    networks:
      - prep-tracker-network

  nginx:
    image: nginx:1.29-alpine
    container_name: prep-tracker-prod-reverse-proxy
    restart: unless-stopped
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - api
    networks:
      - prep-tracker-network

networks:
  prep-tracker-network:
    driver: bridge
